# Generated by Django 4.2.27 on 2026-01-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('capitulo', models.CharField(blank=True, max_length=10, verbose_name='Capítulo')),
                ('concepto', models.CharField(blank=True, max_length=10, verbose_name='Concepto')),
                ('partida_generica', models.CharField(blank=True, max_length=10, verbose_name='Partida Genérica')),
                ('partida_especifica', models.CharField(blank=True, max_length=10, verbose_name='Partida Específica')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'COG',
                'verbose_name_plural': 'COG (Clasificador)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de solicitud')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción general')),
                ('justificacion', models.TextField(blank=True, verbose_name='Justificación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('en_cotizacion', 'En Cotización'), ('cotizado', 'Cotizado'), ('en_autorizacion', 'En Autorización'), ('autorizado', 'Autorizado'), ('en_orden', 'En Orden de Compra'), ('parcial', 'Parcialmente Entregado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total estimado')),
                ('urgente', models.BooleanField(default=False, verbose_name='Urgente')),
                ('fecha_requerida', models.DateField(blank=True, null=True, verbose_name='Fecha requerida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_material', to='areas.area', verbose_name='Área solicitante')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Material',
                'verbose_name_plural': 'Solicitudes de Material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=500, verbose_name='Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Cantidad')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio estimado unitario')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_material', to='procurement.cog', verbose_name='COG')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='procurement.solicitudmaterial', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Material',
                'verbose_name_plural': 'Detalles de Material',
                'ordering': ['id'],
            },
        ),
    ]
