# Generated by Django 4.2.27 on 2026-02-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cog',
            name='palabras_clave',
            field=models.TextField(blank=True, help_text='Términos de búsqueda separados por coma para facilitar la localización del COG', verbose_name='Palabras Clave'),
        ),
    ]
