# Generated by Django 4.2.27 on 2026-03-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_add_palabras_clave_to_cog'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='actividad',
            field=models.TextField(blank=True, help_text='Ej: Apoyar económicamente o en especie a solicitudes procedentes', verbose_name='Actividad o Acción'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='eje_rector',
            field=models.TextField(blank=True, help_text='Ej: Bienestar Social, Ambiente Sano, etc.', verbose_name='Eje Rector'),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='programa_presupuestario',
            field=models.TextField(blank=True, help_text='Ej: Apoyar y subsidiar con recursos económicos a grupos vulnerables', verbose_name='Programa Presupuestario'),
        ),
    ]
