# Generated by Django 4.2.27 on 2026-04-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_solicitudmaterial_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='estado',
            field=models.CharField(choices=[('pendiente_verificacion', 'Pendiente de Verificación INE'), ('ine_rechazada', 'INE Rechazada'), ('borrador', 'Borrador'), ('enviado', 'Enviado'), ('en_cotizacion', 'En Cotización'), ('cotizado', 'Cotizado'), ('en_autorizacion', 'En Autorización'), ('autorizado', 'Autorizado'), ('en_orden', 'En Orden de Compra'), ('parcial', 'Parcialmente Entregado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=30, verbose_name='Estado'),
        ),
    ]
