# Generated by Django 4.2.27 on 2026-01-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('areas', '0001_initial'),
        ('invoices', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaBienes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de recepción')),
                ('fecha_recepcion', models.DateTimeField(verbose_name='Fecha de recepción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('completa', models.BooleanField(default=False, verbose_name='Entrega completa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='invoices.factura', verbose_name='Factura')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='orders.ordencompra', verbose_name='Orden de Compra')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Entrega de Bienes',
                'verbose_name_plural': 'Entregas de Bienes',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='SalidaBienes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de salida')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de salida')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('confirmada', models.BooleanField(default=False, verbose_name='Confirmada por destino')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_almacen', to='areas.area', verbose_name='Almacén origen')),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada por')),
                ('destino_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_recibidas', to='areas.area', verbose_name='Área destino')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Salida de Bienes',
                'verbose_name_plural': 'Salidas de Bienes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=500, verbose_name='Material')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Cantidad')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.salidabienes', verbose_name='Salida')),
            ],
            options={
                'verbose_name': 'Detalle de Salida',
                'verbose_name_plural': 'Detalles de Salida',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/entregas/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='inventory.entregabienes', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Evidencia de Entrega',
                'verbose_name_plural': 'Evidencias de Entrega',
            },
        ),
        migrations.CreateModel(
            name='EntregaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Cantidad recibida')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('condicion_buena', models.BooleanField(default=True, verbose_name='Buena condición')),
                ('observaciones_condicion', models.TextField(blank=True, verbose_name='Observaciones de condición')),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='orders.detalleorden', verbose_name='Detalle de Orden')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.entregabienes', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Detalle de Entrega',
                'verbose_name_plural': 'Detalles de Entrega',
            },
        ),
    ]
