# Generated by Django 4.2.27 on 2026-01-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('presupuesto_anual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Presupuesto anual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_areas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='areas.area', verbose_name='Área padre')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PersonalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=255, verbose_name='Cargo')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Área principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='areas.area', verbose_name='Área')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Personal del Área',
                'verbose_name_plural': 'Personal de las Áreas',
                'unique_together': {('user', 'area')},
            },
        ),
    ]
