# Generated by Django 4.2.30 on 2026-04-30 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0004_add_is_quick_flow'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('fondo_programa', models.CharField(max_length=200)),
                ('tipo_material', models.CharField(max_length=200)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_gasto', to='invoices.factura')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_gasto', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('cog_clave', models.CharField(max_length=20)),
                ('cog_nombre', models.CharField(max_length=200)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('PAGADA', 'Pagada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitud_gasto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_pago', to='treasury.solicitudgasto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitudPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_presupuestaria', models.CharField(max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.area')),
                ('solicitud_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treasury.solicitudpago')),
            ],
            options={
                'ordering': ['area__name'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitudGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_presupuestaria', models.CharField(max_length=200)),
                ('concepto_bien', models.CharField(max_length=200)),
                ('descripcion_adquirido', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.area')),
                ('solicitud_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treasury.solicitudgasto')),
            ],
            options={
                'ordering': ['area__name', 'concepto_bien'],
            },
        ),
    ]
