# Generated by Django 4.2.27 on 2026-01-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('quotations', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_autorizado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto autorizado')),
                ('partida_presupuestal', models.CharField(blank=True, max_length=100, verbose_name='Partida presupuestal')),
                ('fecha_aprobacion', models.DateField(verbose_name='Fecha de aprobación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
            ],
            options={
                'verbose_name': 'Autorización Presupuestal',
                'verbose_name_plural': 'Autorizaciones Presupuestales',
            },
        ),
        migrations.CreateModel(
            name='SolicitudAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto solicitado')),
                ('justificacion', models.TextField(blank=True, verbose_name='Justificación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones', to='quotations.cotizacionmaterial', verbose_name='Cotización seleccionada')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_solicitadas', to='procurement.solicitudmaterial', verbose_name='Solicitud de Material')),
            ],
            options={
                'verbose_name': 'Solicitud de Autorización',
                'verbose_name_plural': 'Solicitudes de Autorización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega esperada')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('condiciones_pago', models.TextField(blank=True, verbose_name='Condiciones de pago')),
                ('lugar_entrega', models.TextField(blank=True, verbose_name='Lugar de entrega')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada por Proveedor'), ('parcial', 'Parcialmente Entregada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, verbose_name='Referencia externa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='orders.autorizacionpresupuestal', verbose_name='Autorización')),
                ('cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='quotations.cotizacionmaterial', verbose_name='Cotización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='companies.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=500, verbose_name='Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Cantidad')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Cantidad recibida')),
                ('detalle_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_orden', to='procurement.detallematerial', verbose_name='Material solicitado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Orden',
            },
        ),
        migrations.AddField(
            model_name='autorizacionpresupuestal',
            name='solicitud_autorizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacion_presupuestal', to='orders.solicitudautorizacion', verbose_name='Solicitud de Autorización'),
        ),
    ]
