# Generated by Django 4.2.27 on 2026-04-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ine_foto',
            field=models.ImageField(blank=True, null=True, upload_to='ine/', verbose_name='Foto de INE'),
        ),
        migrations.AddField(
            model_name='user',
            name='ine_rechazada',
            field=models.BooleanField(default=False, verbose_name='INE rechazada'),
        ),
        migrations.AddField(
            model_name='user',
            name='ine_rechazo_motivo',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo de INE'),
        ),
        migrations.AddField(
            model_name='user',
            name='ine_verificada',
            field=models.BooleanField(default=False, verbose_name='INE verificada'),
        ),
    ]
