# Generated by Django 4.2.27 on 2026-01-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, verbose_name='Nombre Comercial')),
                ('contacto_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre de contacto')),
                ('contacto_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('documentos', models.JSONField(blank=True, default=list, verbose_name='Documentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, verbose_name='Nombre Comercial')),
                ('calle', models.CharField(blank=True, max_length=255, verbose_name='Calle')),
                ('numero_exterior', models.CharField(blank=True, max_length=20, verbose_name='Número Exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=20, verbose_name='Número Interior')),
                ('colonia', models.CharField(blank=True, max_length=255, verbose_name='Colonia')),
                ('municipio', models.CharField(blank=True, max_length=255, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
