# Generated by Django 4.2.27 on 2026-02-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='proveedor_logos/', verbose_name='Logo'),
        ),
    ]
