# Generated by Django 4.2.27 on 2026-03-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_add_palabras_clave_to_cog'),
        ('companies', '0002_company_logo_proveedor_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre del producto/servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('marca', models.CharField(blank=True, max_length=255, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=255, verbose_name='Modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_proveedor', to='procurement.cog', verbose_name='COG')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='companies.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto de Proveedor',
                'verbose_name_plural': 'Productos de Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='productoproveedor',
            constraint=models.UniqueConstraint(fields=('proveedor', 'nombre', 'unidad'), name='unique_producto_proveedor'),
        ),
    ]
