# Generated by Django 4.2.27 on 2026-03-11 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_productoproveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='membrete',
            field=models.ImageField(blank=True, null=True, upload_to='company_membretes/', verbose_name='Membrete Oficial'),
        ),
        migrations.AddField(
            model_name='company',
            name='pie_pagina',
            field=models.ImageField(blank=True, null=True, upload_to='company_pies/', verbose_name='Pie de Página'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='membrete',
            field=models.ImageField(blank=True, null=True, upload_to='proveedor_membretes/', verbose_name='Membrete Oficial'),
        ),
        migrations.CreateModel(
            name='FirmanteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('solicitud', 'Solicitud de Materiales'), ('cotizacion', 'Cotización'), ('solicitud_autorizacion', 'Solicitud de Autorización'), ('autorizacion', 'Autorización Presupuestal'), ('orden_compra', 'Orden de Compra'), ('entrega', 'Entrega/Recepción'), ('salida', 'Salida de Almacén'), ('solicitud_gasto', 'Solicitud del Gasto'), ('solicitud_pago', 'Solicitud de Pago')], max_length=30, verbose_name='Tipo de Documento')),
                ('cargo', models.CharField(help_text='Ej: Sindicatura, Secretario Particular, Tesorero(a) Municipal', max_length=255, verbose_name='Cargo/Puesto')),
                ('nombre', models.CharField(blank=True, help_text='Si se deja vacío se usa el nombre del usuario vinculado', max_length=255, verbose_name='Nombre (fijo)')),
                ('sello_imagen', models.ImageField(blank=True, null=True, upload_to='sellos_firmantes/', verbose_name='Imagen del Sello')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Posición de izquierda a derecha (1, 2, 3...)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmantes', to='companies.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmante_como', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Firmante de Documento',
                'verbose_name_plural': 'Firmantes de Documentos',
                'ordering': ['tipo_documento', 'orden'],
                'unique_together': {('company', 'tipo_documento', 'orden')},
            },
        ),
    ]
