# Generated by Django 4.2.27 on 2026-01-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('solicitud', 'Solicitud de Material'), ('cotizacion', 'Cotización'), ('autorizacion', 'Autorización Presupuestal'), ('orden_compra', 'Orden de Compra'), ('entrega', 'Entrega de Bienes'), ('salida', 'Salida de Bienes'), ('reporte', 'Reporte')], max_length=20, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('pdf_file', models.FileField(upload_to='documents/pdf/', verbose_name='Archivo PDF')),
                ('generated_by_task', models.CharField(blank=True, max_length=100, verbose_name='Task ID')),
                ('template_used', models.CharField(blank=True, max_length=100, verbose_name='Plantilla')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generated', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Documento PDF',
                'verbose_name_plural': 'Documentos PDF',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/files/', verbose_name='Archivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de contenido')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Archivo Media',
                'verbose_name_plural': 'Archivos Media',
            },
        ),
    ]
