# Generated by Django 4.2.27 on 2026-01-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(verbose_name='Fecha de cotización')),
                ('vigencia', models.DateField(blank=True, null=True, verbose_name='Vigencia')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('tiempo_entrega', models.CharField(blank=True, max_length=100, verbose_name='Tiempo de entrega')),
                ('condiciones_pago', models.TextField(blank=True, verbose_name='Condiciones de pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('seleccionada', 'Seleccionada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('documento', models.FileField(blank=True, null=True, upload_to='cotizaciones/', verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='companies.proveedor', verbose_name='Proveedor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='procurement.solicitudmaterial', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=500, verbose_name='Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Cantidad')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='quotations.cotizacionmaterial', verbose_name='Cotización')),
                ('detalle_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='procurement.detallematerial', verbose_name='Detalle de solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
            },
        ),
    ]
