# Generated by Django 4.2.27 on 2026-01-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('areas', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_file', models.FileField(upload_to='facturas/xml/', verbose_name='Archivo XML')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='facturas/pdf/', verbose_name='Archivo PDF')),
                ('uuid_cfdi', models.CharField(blank=True, max_length=36, unique=True, verbose_name='UUID CFDI')),
                ('folio', models.CharField(blank=True, max_length=50, verbose_name='Folio')),
                ('serie', models.CharField(blank=True, max_length=25, verbose_name='Serie')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('rfc_emisor', models.CharField(blank=True, max_length=13, verbose_name='RFC Emisor')),
                ('nombre_emisor', models.CharField(blank=True, max_length=255, verbose_name='Nombre Emisor')),
                ('rfc_receptor', models.CharField(blank=True, max_length=13, verbose_name='RFC Receptor')),
                ('nombre_receptor', models.CharField(blank=True, max_length=255, verbose_name='Nombre Receptor')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Descuento')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA')),
                ('isr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ISR Retenido')),
                ('iva_retenido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA Retenido')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('forma_pago', models.CharField(blank=True, max_length=10, verbose_name='Forma de pago')),
                ('metodo_pago', models.CharField(blank=True, max_length=10, verbose_name='Método de pago')),
                ('moneda', models.CharField(default='MXN', max_length=10, verbose_name='Moneda')),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Tipo de cambio')),
                ('tipo_comprobante', models.CharField(blank=True, max_length=10, verbose_name='Tipo de comprobante')),
                ('uso_cfdi', models.CharField(blank=True, max_length=10, verbose_name='Uso CFDI')),
                ('parsed_json', models.JSONField(blank=True, default=dict, verbose_name='JSON Parseado')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de procesar'), ('procesando', 'Procesando'), ('procesada', 'Procesada'), ('error', 'Error en procesamiento'), ('distribuida', 'Distribuida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='companies.proveedor', verbose_name='Proveedor')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(blank=True, max_length=20, verbose_name='Clave Prod/Serv')),
                ('no_identificacion', models.CharField(blank=True, max_length=100, verbose_name='No. Identificación')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Cantidad')),
                ('clave_unidad', models.CharField(blank=True, max_length=20, verbose_name='Clave Unidad')),
                ('unidad', models.CharField(blank=True, max_length=50, verbose_name='Unidad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('valor_unitario', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Valor unitario')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Importe')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Descuento')),
                ('objeto_imp', models.CharField(blank=True, max_length=5, verbose_name='Objeto de impuesto')),
                ('impuestos', models.JSONField(blank=True, default=dict, verbose_name='Impuestos')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='invoices.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
            },
        ),
        migrations.CreateModel(
            name='DistribucionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Porcentaje')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_distribuidos', to='areas.area', verbose_name='Área')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='invoices.facturadetalle', verbose_name='Concepto')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='invoices.factura', verbose_name='Factura')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_asociados', to='procurement.solicitudmaterial', verbose_name='Solicitud origen')),
            ],
            options={
                'verbose_name': 'Distribución de Gasto',
                'verbose_name_plural': 'Distribuciones de Gasto',
            },
        ),
    ]
