# Generated by Django 4.2.27 on 2026-01-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='uuid_cfdi',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='UUID CFDI'),
        ),
    ]
