# Generated by Django 4.2.27 on 2026-01-28 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('invoices', '0002_allow_null_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='companies.proveedor', verbose_name='Proveedor'),
        ),
    ]
