# Generated by Django 4.2.27 on 2026-02-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_optional_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='is_quick_flow',
            field=models.BooleanField(default=False, help_text='Indica si la factura fue procesada mediante el flujo rápido (sin solicitud/orden previa)', verbose_name='Flujo rápido'),
        ),
    ]
