# Generated by Django 4.2.27 on 2026-04-14 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: "Plantilla 2025"', max_length=255, verbose_name='Nombre')),
                ('ejercicio_fiscal', models.IntegerField(help_text='Ej: 2025', verbose_name='Ejercicio Fiscal')),
                ('entidad_federativa', models.CharField(max_length=10, verbose_name='Entidad Federativa')),
                ('clasificador_administrativo', models.CharField(max_length=20, verbose_name='Clasificador Administrativo')),
                ('no_municipio_ramo', models.CharField(max_length=20, verbose_name='No. Municipio / Ramo')),
                ('unidad_administrativa', models.CharField(max_length=20, verbose_name='Unidad Administrativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_presupuestales', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Plantilla Presupuestal',
                'verbose_name_plural': 'Plantillas Presupuestales',
                'ordering': ['-ejercicio_fiscal', '-created_at'],
                'unique_together': {('tenant', 'nombre', 'ejercicio_fiscal')},
            },
        ),
        migrations.CreateModel(
            name='ItemClavePres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_ejecutora_gasto', models.CharField(max_length=20, verbose_name='Unidad Ejecutora del Gasto')),
                ('cog', models.CharField(help_text='Clasificador por Objeto del Gasto, ej: "21611"', max_length=10, verbose_name='COG')),
                ('cog_fondo', models.CharField(help_text='4° dígito del COG — fondo', max_length=5, verbose_name='COG Fondo')),
                ('cog_desagregacion', models.CharField(help_text='3° dígito del COG — desagregación', max_length=5, verbose_name='COG Desagregación')),
                ('clasificador_programatico', models.CharField(max_length=20, verbose_name='Clasificador Programático')),
                ('tipo_gasto', models.CharField(max_length=5, verbose_name='Tipo de Gasto')),
                ('finalidad_funcion', models.CharField(max_length=10, verbose_name='Finalidad / Función')),
                ('fuente_financiamiento', models.CharField(max_length=10, verbose_name='Fuente de Financiamiento')),
                ('clasificador_economico', models.CharField(max_length=20, verbose_name='Clasificador Económico')),
                ('actividad_institucional', models.CharField(max_length=20, verbose_name='Actividad Institucional')),
                ('programa_presupuestario', models.CharField(max_length=20, verbose_name='Programa Presupuestario')),
                ('accion', models.CharField(max_length=10, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.plantillapresupuestal', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Clave Presupuestaria',
                'verbose_name_plural': 'Claves Presupuestarias',
                'ordering': ['id'],
            },
        ),
    ]
